## Tarea-1

# Aprendizaje automático
# Tarea-1

Prof. Felipe Meza Obando,
Instituto Tecnológico de Costa Rica, 

Medio de entrega: Link de GitHub

Entregables: Un archivo jupyter ( .IPYNB ). 

Modo de trabajo: Parejas:
Estudiantes:

Yu Hung Yeh

José Alberto Raygada Agüero

---

Objetivo
El objetivo de esta Tarea 1 consiste en normalizar y estandarizar el set
de datos de daily-min-temperatures.csv de forma manual y automática a partir de scikit-learn
o la librería que considere apropiada.

---


### Primero cargamos las librerías

In [1]:
# !pip install torch

%matplotlib inline

import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import sklearn
from sklearn.preprocessing import MinMaxScaler
import sklearn.preprocessing
import torch as torch


#Funciones
def bold(t):
    """
    Funcion para formatear en negrita el texto.
    t = cualquier dato
    """
    return "\033[1m" + str(t) + "\033[0m"

def newline():
    """
    Funcion para imprimir cambio de linea
    """
    print("\r\n")


### Luego cargamos el archivo como un dataframe de csv

In [2]:
df = pd.read_csv(r"daily-min-temperatures.txt")
df.head()

Date  Temp
0  1981-01-01  20.7
1  1981-01-02  17.9
2  1981-01-03  18.8
3  1981-01-04  14.6
4  1981-01-05  15.8

### Se selecciona únicamente la columna de temperatura que es el dato que podemos estandarizar

In [3]:
print(bold("Estandarización y normalización automática"))
print("----------------------------------------------")
newline()    

feature = df[["Temp"]]

scaler = MinMaxScaler()
nombreColumnas = feature.columns.to_numpy()
datosEscalados = pd.DataFrame(scaler.fit_transform(feature), columns = nombreColumnas)

print(bold("Features estandarizados y normalizados"))
newline()    
print(datosEscalados)


Estandarización y normalización automática
----------------------------------------------


Features estandarizados y normalizados


          Temp
0     0.787072
1     0.680608
2     0.714829
3     0.555133
4     0.600760
...        ...
3645  0.532319
3646  0.517110
3647  0.513308
3648  0.596958
3649  0.494297

[3650 rows x 1 columns]


In [24]:
# Escalamiento mim max manual

minimo = feature.min()
maximo = feature.max()

minmax = (feature - minimo) / (maximo - minimo)
print(minmax)

          Temp
0     0.787072
1     0.680608
2     0.714829
3     0.555133
4     0.600760
...        ...
3645  0.532319
3646  0.517110
3647  0.513308
3648  0.596958
3649  0.494297

[3650 rows x 1 columns]


In [4]:
def norm2(v):
    """
    Funcion para calculo de distancia Eucliciana o l2
    v = vector
    """
    sum = torch.tensor(0)
    for x in v:
        sum = sum + x ** 2
    
    return sum.sqrt()


feature_tensor = torch.tensor(feature.values)

resultado_manual = norm2(feature_tensor)

print(bold("Estandarización y normalización manual"))
print("----------------------------------------------")
newline()  

print(resultado_manual)

Estandarización y normalización manual
----------------------------------------------


tensor([718.7064], dtype=torch.float64)


In [33]:
# Normalización de los datos (automático)

from sklearn.preprocessing import Normalizer

feature_tensor = torch.tensor(feature.values)

normalizador = Normalizer(norm="l2")

normalizados_automatico = normalizador.transform(feature_tensor)

print(bold("Normalización automática"))
print("----------------------------------------------")
print(normalizados_automatico)

Normalización automática
----------------------------------------------
[[1.]
 [1.]
 [1.]
 ...
 [1.]
 [1.]
 [1.]]


In [32]:
# Normalización de los datos (manual)

import math as math

def my_norma2(v1):
    norma2 = math.sqrt(sum(i*i for i in v1))
    return norma2

normalizados_manual = my_norma2(feature_tensor)
print(normalizados_manual)


718.7063517181411


In [40]:
promedio = minmax.mean()
desv_std = minmax.std()

estandarizado = ((minmax - promedio) / desv_std)

In [43]:
print(feature)
print(bold("\nEstandarizado manual: "))
print("----------------------------------------------\n")
print(estandarizado)

      Temp
0     20.7
1     17.9
2     18.8
3     14.6
4     15.8
...    ...
3645  14.0
3646  13.6
3647  13.5
3648  15.7
3649  13.0

[3650 rows x 1 columns]

Estandarizado manual: 
----------------------------------------------

          Temp
0     2.338563
1     1.650913
2     1.871943
3     0.840467
4     1.135175
...        ...
3645  0.693114
3646  0.594878
3647  0.570319
3648  1.110616
3649  0.447524

[3650 rows x 1 columns]


In [42]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()

estandarizado_automatico = sc.fit_transform(feature)

print(bold("Estandarizado automático: "))
print("----------------------------------------------\n")
print(estandarizado_automatico)

Estandarizado automático: 
----------------------------------------------

[[2.33888328]
 [1.65113873]
 [1.87219948]
 ...
 [0.5703973 ]
 [1.11076801]
 [0.44758577]]
